run:
  timezone: America/New_York
  report_hour_local: 10          # ya ajustado a 10:00 ET
  min_rows_in_report: 10
  alert_threshold_score: 70
  signals_only: true             # <- NUEVO: para que el reporte solo sea señales

watchlist:
  - id: bitcoin
    name: BTC
    defillama_slug: bitcoin
  - id: ethereum
    name: ETH
    defillama_slug: ethereum
  - id: solana
    name: SOL
    defillama_slug: solana
  - id: aave
    name: AAVE
    defillama_slug: aave
  - id: ripple
    name: XRP            # ← sin defillama_slug
  - id: cardano
    name: ADA
    defillama_slug: cardano
  - id: avalanche-2
    name: AVAX
    defillama_slug: avalanche
  - id: polkadot
    name: DOT            # ← sin defillama_slug
  - id: chainlink
    name: LINK
    defillama_slug: chainlink
  - id: uniswap
    name: UNI
    defillama_slug: uniswap
  - id: tether
    name: USDT
    defillama_slug: tether
  - id: binancecoin
    name: BNB
    defillama_slug: binancecoin
  - id: polygon-ecosystem-token
    name: POL           # (antes MATIC)
    defillama_slug: polygon
  - id: toncoin
    name: TON
    defillama_slug: toncoin
  - id: litecoin
    name: LTC
    defillama_slug: litecoin
  - id: tron
    name: TRX
    defillama_slug: tron
    
notify:
  telegram:
    enabled: true
    daily_actions: true   # <- enviar SIEMPRE el resumen Buy/Sell
