run:
  timezone: America/New_York
  report_hour_local: 10          # ya ajustado a 10:00 ET
  min_rows_in_report: 10
  alert_threshold_score: 70
  signals_only: true             # <- NUEVO: para que el reporte solo sea señales

watchlist:
  - id: bitcoin      # BTC
    name: BTC
    defillama_slug: bitcoin
  - id: ethereum     # ETH
    name: ETH
    defillama_slug: ethereum
  - id: solana       # SOL
    name: SOL
    defillama_slug: solana
  - id: aave         # AAVE
    name: AAVE
    defillama_slug: aave
  - id: ripple       # XRP
    name: XRP
    defillama_slug: ripple
  - id: cardano      # ADA
    name: ADA
    defillama_slug: cardano
  - id: avalanche-2  # AVAX
    name: AVAX
    defillama_slug: avalanche
  - id: polkadot     # DOT
    name: DOT
    defillama_slug: polkadot
  - id: chainlink    # LINK
    name: LINK
    defillama_slug: chainlink
  - id: uniswap      # UNI
    name: UNI
    defillama_slug: uniswap

notify:
  telegram:
    enabled: true
    daily_actions: true   # <- enviar SIEMPRE el resumen Buy/Sell
