run:
  timezone: America/New_York
  report_hour_local: 7
  min_rows_in_report: 10
  alert_threshold_score: 1

watchlist:
  - id: bitcoin
    name: BTC
    defillama_slug: bitcoin
  - id: ethereum
    name: ETH
    defillama_slug: ethereum
  - id: solana
    name: SOL
    defillama_slug: solana
  - id: arbitrum
    name: ARB
    defillama_slug: arbitrum
  - id: optimism
    name: OP
    defillama_slug: optimism
  - id: uniswap
    name: UNI
    defillama_slug: uniswap
  - id: aave
    name: AAVE
    defillama_slug: aave

notify:
  telegram:
    enabled: true
