run:
  discovery_enabled: true
  discovery_limit: 100        # cuántos de CG por volumen
  discovery_min_volume_usd: 20000000  # umbral extra para discovery
  discovery_require_coinbase_usd: true  # filtra a los que tengan par -USD en Coinbase
  quick_trade:
    buy_score_min: 25         # igual que tu min_score “señal”
    buy_chg_24h_min: 0.0      # >= 0% en 24h
    buy_chg_7d_min: 0.0       # >= 0% en 7d
    sell_score_max: 10        # si cae por debajo → sugerir salida
    take_profit_pct: 0.20     # +20% TP
    stop_pct: 0.10            # -10% “stop” sugerido
  timezone: America/New_York
  report_hour_local: 10
  top_n: 5                     # ← cuántos máximos mostrar como señales fuertes
  signals_only: true           # ← solo señales (sin bloques extra)
  min_score: 25                # ← score mínimo para considerar
  min_volume_24h_usd: 10000000 # ← evita ilíquidos
  min_tvl_growth_7d: -0.02     # ← requiere TVL plano/creciente en 7d (ajusta si quieres)
  exclude_stables: true
  stables:
    - USDT
    - USDC
    - DAI
    - TUSD
    - USDP
    - FDUSD

  # Ponderación de 14 días (para weighted-14d)
  weights_mode: exp    # "exp" (recomendado) o "fixed"
  weights_alpha: 0.55  # si weights_mode=exp, numero grande le da menos importancia a hoy y mas hace 14 dias. Numero bajo al reves: 0.8 = hoy: 20.9%, dia 14: 1.1%. 0.6 = Hoy: 40%, dia 14: 0.05%
  # weights_fixed: [40,20,10,7,5,4,3,3,2,2,1,1,1,1]  # si usas "fixed"

watchlist:
  - id: aave
    name: AAVE
    defillama_slug: aave        # ✅ protocolo
  - id: uniswap
    name: UNI
    defillama_slug: uniswap     # ✅ protocolo
  - id: bitcoin
    name: BTC                   # ❌ no pongas slug de protocol
  - id: ethereum
    name: ETH                   # ❌
  - id: solana
    name: SOL                   # ❌
  - id: ripple
    name: XRP                   # ❌
  - id: cardano
    name: ADA                   # ❌
  - id: avalanche-2
    name: AVAX                  # ❌
  - id: polkadot
    name: DOT                   # ❌
  - id: chainlink
    name: LINK                  # ❌
  - id: tether
    name: USDT                  # ❌ (no queremos su “protocol”)
  - id: binancecoin
    name: BNB                   # ❌
  - id: polygon-ecosystem-token
    name: POL                   # ❌
  - id: toncoin
    name: TON                   # ❌
  - id: litecoin
    name: LTC                   # ❌
  - id: tron
    name: TRX                   # ❌
    
  # Nuevas
  - id: arbitrum
    name: ARB
    defillama_slug: arbitrum   # ✅ mantener, aporta TVL
  - id: optimism
    name: OP
    defillama_slug: optimism   # ✅ mantener, aporta TVL
  - id: matic-network
    name: MATIC
    defillama_slug: polygon    # ✅ mantener, aporta TVL

  # Altcoins muy negociadas en Coinbase (sin DeFi relevante → remover slug)
  - id: dogecoin
    name: DOGE
  - id: shiba-inu
    name: SHIB
  - id: bitcoin-cash
    name: BCH
  - id: near-protocol
    name: NEAR     # ⚠️ tiene algo de DeFi, pero en DeFiLlama el slug "near" a veces falla → mejor dejar limpio
  - id: immutable-x
    name: IMX
  - id: render-token
    name: RNDR
  - id: injective-protocol
    name: INJ     # ⚠️ también aparece en DeFiLlama, pero con slug distinto → mejor dejar limpio

  # Stable de referencia (se excluye de señales, útil para parking)
  - id: usd-coin
    name: USDC

notify:
  telegram:
    enabled: false            # ← desactiva cualquier “acciones diarias” automáticas
    daily_actions: false
