run:
  timezone: America/New_York
  report_hour_local: 10
  top_n: 10                   # ← cuántos máximos mostrar como señales fuertes
  signals_only: true          # ← solo señales (sin bloques extra)
  min_score: 70               # ← score mínimo para considerar
  min_volume_24h_usd: 1000000 # ← evita ilíquidos
  min_tvl_growth_7d: 0.0      # ← requiere TVL plano/creciente en 7d (ajusta si quieres)
  exclude_stables: true
  stables:
    - USDT
    - USDC
    - DAI
    - TUSD
    - USDP
    - FDUSD

  # Ponderación de 14 días (para weighted-14d)
  weights_mode: exp           # "exp" (recomendado) o "fixed"
  weights_alpha: 0.8          # si weights_mode=exp
  # weights_fixed: [40,20,10,7,5,4,3,3,2,2,1,1,1,1]  # si usas "fixed"

watchlist:
  - id: bitcoin
    name: BTC
    defillama_slug: bitcoin
  - id: ethereum
    name: ETH
    defillama_slug: ethereum
  - id: solana
    name: SOL
    defillama_slug: solana
  - id: aave
    name: AAVE
    defillama_slug: aave
  - id: ripple
    name: XRP
  - id: cardano
    name: ADA
    defillama_slug: cardano
  - id: avalanche-2
    name: AVAX
    defillama_slug: avalanche
  - id: polkadot
    name: DOT
    defillama_slug: polkadot
  - id: chainlink
    name: LINK
    defillama_slug: chainlink
  - id: uniswap
    name: UNI
    defillama_slug: uniswap
  - id: tether
    name: USDT
    defillama_slug: tether
  - id: binancecoin
    name: BNB
    defillama_slug: binancecoin
  - id: polygon-ecosystem-token
    name: POL
    defillama_slug: polygon
  - id: toncoin
    name: TON
    defillama_slug: toncoin
  - id: litecoin
    name: LTC
    defillama_slug: litecoin
  - id: tron
    name: TRX
    defillama_slug: tron

notify:
  telegram:
    enabled: false            # ← desactiva cualquier “acciones diarias” automáticas
    daily_actions: false
