run:
  timezone: America/New_York
  report_hour_local: 10
  top_n: 5                   # ← cuántos máximos mostrar como señales fuertes
  signals_only: true          # ← solo señales (sin bloques extra)
  min_score: 32               # ← score mínimo para considerar
  min_volume_24h_usd: 750000 # ← evita ilíquidos
  min_tvl_growth_7d: -0.02      # ← requiere TVL plano/creciente en 7d (ajusta si quieres)
  exclude_stables: true
  stables:
    - USDT
    - USDC
    - DAI
    - TUSD
    - USDP
    - FDUSD

  # Ponderación de 14 días (para weighted-14d)
  weights_mode: exp           # "exp" (recomendado) o "fixed"
  weights_alpha: 0.8          # si weights_mode=exp
  # weights_fixed: [40,20,10,7,5,4,3,3,2,2,1,1,1,1]  # si usas "fixed"

watchlist:
  - id: aave
    name: AAVE
    defillama_slug: aave        # ✅ protocolo
  - id: uniswap
    name: UNI
    defillama_slug: uniswap     # ✅ protocolo
  - id: bitcoin
    name: BTC                   # ❌ no pongas slug de protocol
  - id: ethereum
    name: ETH                   # ❌
  - id: solana
    name: SOL                   # ❌
  - id: ripple
    name: XRP                   # ❌
  - id: cardano
    name: ADA                   # ❌
  - id: avalanche-2
    name: AVAX                  # ❌
  - id: polkadot
    name: DOT                   # ❌
  - id: chainlink
    name: LINK                  # ❌
  - id: tether
    name: USDT                  # ❌ (no queremos su “protocol”)
  - id: binancecoin
    name: BNB                   # ❌
  - id: polygon-ecosystem-token
    name: POL                   # ❌
  - id: toncoin
    name: TON                   # ❌
  - id: litecoin
    name: LTC                   # ❌
  - id: tron
    name: TRX                   # ❌

notify:
  telegram:
    enabled: false            # ← desactiva cualquier “acciones diarias” automáticas
    daily_actions: false
