name: publish-autoscan

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -e
          pip install -r requirements.txt

      - name: Build reports (generate out/latest.*)
        run: |
          set -e
          python main_known.py

      - name: Publish to docs
        run: |
          set -e
          mkdir -p docs
          cp -f out/latest.md docs/latest.md
          cp -f out/latest.json docs/latest.json
          cp -f out/report-*.md docs/ 2>/dev/null || true
          cp -f out/report-*.json docs/ 2>/dev/null || true

      - name: Prune history (keep last 14 days)
        run: |
          set -e
          # Mantener los 14 más recientes por nombre (report-YYYY-MM-DD.*)
          for ext in md json; do
            ls -1 docs/report-*.${ext} 2>/dev/null | sort | head -n -14 | xargs -r rm -f
          done

      - name: Commit reports
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "publish: latest + prune history" || echo "No changes to commit"
          git push

      - name: Debug listing
        run: |
          echo "OUT:"
          ls -lah out || true
          echo "DOCS:"
          ls -lah docs || true

      - name: Commit reports
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "publish: update latest" || echo "No changes to commit"
          git push
