name: cripto-publish

on:
  schedule:
    - cron: '0 14 * * *'   # 10:00 ET durante DST (EDT, UTC-4)
    - cron: '0 15 * * *'   # 10:00 ET durante EST (UTC-5)
  workflow_dispatch:

concurrency:
  group: publish-autoscan
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Evitar doble corrida en días con 2 triggers: si ya existe el reporte de hoy, salgo.
      - name: Skip if today's report already exists
        run: |
          set -e
          d=$(date -u +%F)
          if [ -f docs/report-$d.md ]; then
            echo "Report for $d already exists. Skipping."
            exit 0
          fi

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -e
          pip install -r requirements.txt

      - name: Build reports (generate out/latest.*)
        run: |
          set -e
          python main_known.py

      - name: Publish to docs
        run: |
          set -e
          mkdir -p docs
          cp -f out/latest.md docs/latest.md
          cp -f out/latest.json docs/latest.json
          cp -f out/report-*.md docs/ 2>/dev/null || true
          cp -f out/report-*.json docs/ 2>/dev/null || true

      - name: Prune history (keep last 14 days)
        run: |
          set -e
          for ext in md json; do
            ls -1 docs/report-*.${ext} 2>/dev/null | sort | head -n -14 | xargs -r rm -f
          done

      - name: Commit reports
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "publish: latest + prune history" || echo "No changes to commit"
          git push

      - name: Debug listing
        run: |
          echo "OUT:"
          ls -lah out || true
          echo "DOCS:"
          ls -lah docs || true
