name: Crypto Autoscan
  run: |
    python - << 'PY'
    import json, sys, pathlib
    p = pathlib.Path("out/latest.json")
    data = json.loads(p.read_text(encoding="utf-8"))
    assert "projects" in data and isinstance(data["projects"], list), "Invalid payload"
    PY
