name: daily-known-scan


on:
schedule:
- cron: "5 11 * * *" # 11:05 UTC ~= 07:05 America/New_York
workflow_dispatch: {}


jobs:
run:
runs-on: ubuntu-latest
permissions:
contents: write # para commitear reportes en /out
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
with:
python-version: '3.11'
- name: Install deps
run: |
pip install -r requirements.txt
- name: Run scan
env:
COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
run: |
python main_known.py
- name: Make latest alias
run: |
d=$(date -u +%F)
cp out/report-$d.md out/latest.md || true
cp out/report-$d.json out/latest.json || true
- name: Commit reports
run: |
git config user.name "github-actions"
git config user.email "actions@github.com"
git add out/*.md out/*.json || true
git commit -m "chore: daily report" || true
git push
