name: publish-autoscan

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -e
          pip install -r requirements.txt

      - name: Build reports (generate out/latest.*)
        run: |
          set -e
          python main_known.py

      - name: Publish to docs
        run: |
          set -e
          mkdir -p docs
          cp -f out/latest.md docs/latest.md
          cp -f out/latest.json docs/latest.json
          # aseguro .nojekyll e index.md para Pages
          [ -f docs/.nojekyll ] || printf '' > docs/.nojekyll
          if [ ! -f docs/index.md ]; then
            printf '# Autoscan\n- [Reporte más reciente](./latest.md)\n- [JSON estructurado](./latest.json)\n' > docs/index.md
          fi

      - name: Debug listing
        run: |
          echo "OUT:"
          ls -lah out || true
          echo "DOCS:"
          ls -lah docs || true

      - name: Commit reports
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "publish: update latest" || echo "No changes to commit"
          git push
